# Generated by Django 6.0.3 on 2026-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='job_title', max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
