import os
"""
Django settings for ems_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

#Build paths 
BASE_DIR = Path(__file__).resolve().parent.parent

#keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+m_63nvyu!q$*j3+2og37d=2)+l*1c5_#e2##96vv(%wd3k3n8'

#Enables debug mode
DEBUG = True

#Allowed host/domain names
ALLOWED_HOSTS = []

#Installs applications
INSTALLED_APPS = [
    #Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #Custom apps
    'users',
    'finance',
    'jobs',
]

#Custom user model
AUTH_USER_MODEL = 'users.User'

#Middleware components
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#Main URL configuration
ROOT_URLCONF = 'ems_project.urls'

#Template configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        #Global templates directory
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #Search templates inside app folders
        'APP_DIRS': True,
        
        'OPTIONS': {
            'context_processors': [
                #Makes request object available in templates
                'django.template.context_processors.request',
                #Provides authentication data
                'django.contrib.auth.context_processors.auth',
                #Enables Django messages framework
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI application entry point
WSGI_APPLICATION = 'ems_project.wsgi.application'



#Database configuration (MySQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'EMS_db',
        'USER': 'root',
        'PASSWORD': 'MySQL@123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    } 
}


#Password validation rules
AUTH_PASSWORD_VALIDATORS = [
    {
        #Prevents passwords similar to user information
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        #Enforces minimum password length
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        #Blocks common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        #Prevents numeric-only passwords
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#Internationalization settings
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
#Additional static files directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#Authentication backend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

#Session management settings

#End session when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#Session timeout after 10 minutes of inactivity
SESSION_COOKIE_AGE = 600  

#Refresh session expiry on every request
SESSION_SAVE_EVERY_REQUEST = True

#Redirects unauthenticated users to login page
LOGIN_URL = 'login'